ComoQuieras/ComoQuieras/urls.py
from django.contrib import admin
from django.urls import path, include

from Cometela.carrito import Carrito
from Cometela.views import ajax_agregar_vianda, ajax_restar_vianda, tienda, agregar_vianda, eliminar_vianda, restar_vianda, limpiar_carrito, cargar_vianda, cargar_semana, desactivar_viandas, rrhh, editar_semana

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tienda, name = "Tienda"),
    #path('agregar/<int:vianda_tamaño_id>/', agregar_vianda, name="Add"),
    path('ajax/agregar/', ajax_agregar_vianda, name="Add"),
    path('ajax/restar/', ajax_restar_vianda, name="Sub"),
    path('eliminar/<int:vianda_tamaño_id>/', eliminar_vianda, name="Del"),
    #path('restar/<int:vianda_tamaño_id>/', restar_vianda, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
    #path('cargar/', cargar_vianda, name="Cargar"),
    path('cargar_semana/', cargar_semana, name="Cargar Semana"),
    path('editar_semana/', editar_semana, name="Editar Semana"),
    path('desactivar_viandas/', desactivar_viandas, name="Desactivar Viandas"),
    path('rrhh/', rrhh, name="Recursos Humanos"),

    path('autenticacion/', include('autenticacion.urls')),

    path('pedidos/', include('pedidos.urls')),

    path('reports/', include('reports.urls')),
]

ComoQuieras/urls.py
from django.contrib import admin
from django.urls import path, include

from Cometela.carrito import Carrito
from Cometela.views import tienda, agregar_vianda, eliminar_vianda, restar_vianda, limpiar_carrito, cargar_vianda, cargar_semana, desactivar_viandas, rrhh, editar_semana

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', tienda, name = "Tienda"),
    path('agregar/<int:vianda_tamaño_id>/', agregar_vianda, name="Add"),
    path('eliminar/<int:vianda_tamaño_id>/', eliminar_vianda, name="Del"),
    path('restar/<int:vianda_tamaño_id>/', restar_vianda, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
    #path('cargar/', cargar_vianda, name="Cargar"),
    path('cargar_semana/', cargar_semana, name="Cargar Semana"),
    path('editar_semana/', editar_semana, name="Editar Semana"),
    path('desactivar_viandas/', desactivar_viandas, name="Desactivar Viandas"),
    path('rrhh/', rrhh, name="Recursos Humanos"),

    path('autenticacion/', include('autenticacion.urls')),

    path('pedidos/', include('pedidos.urls')),

    path('reports/', include('reports.urls')),

]

pedidos/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('',views.procesar_pedido, name="procesar_pedido"),
    path('historial', views.mostrar_pedidos, name="mostrar_pedidos"),
    path('pedidos_activos', views.mostrar_pedidos_rrhh, name="mostrar_pedidos_activos"),
]

Cometela/forms.py
from django import forms
from django.forms import formset_factory

from Cometela.models import Vianda

class FormCargaVianda(forms.ModelForm):

    class Meta:
        model = Vianda
        
        fields = ('dia', 'fecha','descripcion','tipo' )

        def __init__(self, *args, **kwargs):
            super(FormCargaVianda, self).__init__(*args, **kwargs)

            self.fields['dia'].widget.attrs['class'] = 'form-control'
            self.fields['dia'].widget.attrs['placeholder'] = "DIA"

            self.fields['fecha'].widget.attrs['class'] = 'text'
            self.fields['fecha'].widget.attrs['placeholder'] = "Fecha"

            self.fields['descripcion'].widget.attrs['class'] = 'form-control'
            self.fields['descripcion'].widget.attrs['placeholder'] = "Menú"

            self.fields['tipo'].widget.attrs['class'] = 'form-control'
            self.fields['tipo'].widget.attrs['placeholder'] = "Tipo"

class FormCargaSemana(forms.Form):

    precio_media = forms.IntegerField()
    precio_entera = forms.IntegerField()

    #LUNES
    fecha1 = forms.DateField()
    menu1 = forms.CharField(max_length=250)
    menu2 = forms.CharField(max_length=250)
    menu3 = forms.CharField(max_length=250)

    #MARTES
    fecha2 = forms.DateField()
    menu4 = forms.CharField(max_length=250)
    menu5 = forms.CharField(max_length=250)
    menu6 = forms.CharField(max_length=250)

    """
    #MIERCOLES
    fecha3 = forms.DateField()
    menu7 = forms.CharField(max_length=250)
    menu8 = forms.CharField(max_length=250)
    menu9 = forms.CharField(max_length=250)

    #JUEVES
    fecha4 = forms.DateField()
    menu10 = forms.CharField(max_length=250)
    menu11 = forms.CharField(max_length=250)
    menu12 = forms.CharField(max_length=250)

    #VIERNES
    fecha5 = forms.DateField()
    menu13 = forms.CharField(max_length=250)
    menu14 = forms.CharField(max_length=250)
    menu15 = forms.CharField(max_length=250)
    """

ComoQuieras/Cometela/forms.py
from django import forms
from django.forms import formset_factory

from Cometela.models import Vianda

class FormCargaVianda(forms.ModelForm):

    class Meta:
        model = Vianda
        
        fields = ('dia', 'fecha','descripcion','tipo' )

        def __init__(self, *args, **kwargs):
            super(FormCargaVianda, self).__init__(*args, **kwargs)

            self.fields['dia'].widget.attrs['class'] = 'form-control'
            self.fields['dia'].widget.attrs['placeholder'] = "DIA"

            self.fields['fecha'].widget.attrs['class'] = 'text'
            self.fields['fecha'].widget.attrs['placeholder'] = "Fecha"

            self.fields['descripcion'].widget.attrs['class'] = 'form-control'
            self.fields['descripcion'].widget.attrs['placeholder'] = "Menú"

            self.fields['tipo'].widget.attrs['class'] = 'form-control'
            self.fields['tipo'].widget.attrs['placeholder'] = "Tipo"

#TODO ver esto
class FormCargaSemana(forms.Form):

    precio_media = forms.IntegerField()
    precio_entera = forms.IntegerField()

    #LUNES
    fecha1 = forms.DateField()
    menu1 = forms.CharField(max_length=250)
    menu2 = forms.CharField(max_length=250)
    menu3 = forms.CharField(max_length=250)

    #MARTES
    fecha2 = forms.DateField()
    menu4 = forms.CharField(max_length=250)
    menu5 = forms.CharField(max_length=250)
    menu6 = forms.CharField(max_length=250)
    
    #MIERCOLES
    fecha3 = forms.DateField()
    menu7 = forms.CharField(max_length=250)
    menu8 = forms.CharField(max_length=250)
    menu9 = forms.CharField(max_length=250)

    #JUEVES
    fecha4 = forms.DateField()
    menu10 = forms.CharField(max_length=250)
    menu11 = forms.CharField(max_length=250)
    menu12 = forms.CharField(max_length=250)

    #VIERNES
    fecha5 = forms.DateField()
    menu13 = forms.CharField(max_length=250)
    menu14 = forms.CharField(max_length=250)
    menu15 = forms.CharField(max_length=250)
    

Cometela/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from datetime import datetime
# Create your views here.

from Cometela.models import Vianda, Tamaño, ViandaTamaño
from Cometela.carrito import Carrito
from Cometela.forms import FormCargaVianda, FormCargaSemana
from pedidos.models import Pedido

from django.http import JsonResponse


#Necesitas estar logueado para acceder a la tienda
@login_required(login_url="/autenticacion/iniciar_sesion")
def tienda(request):
    #Si el usuario logueado es de RRHH, no accede a la tienda sino que al panel de rrhh
    if (es_rrhh(request.user)):
        return rrhh(request)
    
    #TODO deberiamos contemplar que el usuario pueda modificar su pedido¿?
    #Si el usuario ya tiene un pedido activo, no puede realizar otro
    if (tiene_pedido_activo(request.user)):
        return render(request, "pedido_realizado.html")

    viandas = Vianda.objects.all()
    tamaños = Tamaño.objects.all()
    viandas_tamaños = ViandaTamaño.objects.all()

    return render(request, "viandas.html", {'viandas': viandas, 'tamaños': tamaños, 'viandas_tamaños': viandas_tamaños})

#Control de que el usuario ya tenga un pedido activo
def tiene_pedido_activo(user):
    pedidos = Pedido.objects.filter(user=user).filter(estado='ACTIVO')
    if len(pedidos) == 1:
        return True
    return False

def agregar_vianda(request, vianda_tamaño_id):
    carrito = Carrito(request)
    vianda_tamaño = ViandaTamaño.objects.get(id=vianda_tamaño_id)
    carrito.agregar(vianda_tamaño)
    return redirect("Tienda")

def eliminar_vianda(request, vianda_tamaño_id):
    carrito = Carrito(request)
    vianda_tamaño = ViandaTamaño.objects.get(id=vianda_tamaño_id)
    carrito.eliminar(vianda_tamaño)
    return redirect("Tienda")

def restar_vianda(request, vianda_tamaño_id):
    carrito = Carrito(request)
    vianda_tamaño = ViandaTamaño.objects.get(id=vianda_tamaño_id)
    carrito.restar(vianda_tamaño)
    return redirect("Tienda")

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect("Tienda")

#Cargar una vianda para probar (SACAR)
def cargar_vianda(request):

    if request.method == "POST":

        form = FormCargaVianda(request.POST)
    
        if form.is_valid():
            nueva_vianda = form.save(commit=False)
            Vianda.objects.create(
                estado = 'ACTIVA',
                dia = nueva_vianda.dia,
                fecha = nueva_vianda.fecha,
                descripcion = nueva_vianda.descripcion,
                tipo = nueva_vianda.tipo,
            )
    else:
        form = FormCargaVianda()

    return render(request, 'create.html', {"form": form})

#Control de que el usuario pertenezca al grupo RRHH
def es_rrhh(user):
    return user.groups.filter(name__in=['RRHH'])

#Vista RRHH
@user_passes_test(es_rrhh)
def rrhh(request):
    viandas_activas = Vianda.objects.filter(estado='ACTIVA')
    permite_carga = True
    if len(viandas_activas)>0:
            permite_carga = False

    return render(request, "rrhh_inicio.html", {'permite_carga': permite_carga, 'viandas':viandas_activas})

##################  VER ESTO  ##################
#Cargar las viandas de la semana
@user_passes_test(es_rrhh)
def cargar_semana(request):
    
    if request.method == "POST":

        form = FormCargaSemana(request.POST)

        if form.is_valid():
            tamaño1 = Tamaño()
            tamaño2 = Tamaño()
            vianda1 = Vianda()
            vianda2 = Vianda()
            vianda3 = Vianda()
            vianda4 = Vianda()
            vianda5 = Vianda()
            vianda6 = Vianda()
            vianda7 = Vianda()
            vianda8 = Vianda()
            vianda9 = Vianda()
            vianda10 = Vianda()
            vianda11 = Vianda()
            vianda12 = Vianda()
            vianda13 = Vianda()
            vianda14 = Vianda()
            vianda15 = Vianda()
            
            #PRECIOS
            tamaño1.tamaño = 'MEDIA'
            tamaño1.precio = request.POST["precio_media"]
            tamaño1.estado = 'ACTIVA'
            tamaño1.save()
            tamaño2.tamaño = 'ENTERA'
            tamaño2.precio = request.POST["precio_entera"]
            tamaño2.estado = 'ACTIVA'
            tamaño2.save()

            #LUNES
            vianda1.estado='ACTIVA'
            vianda1.dia = 'LUNES'
            vianda1.fecha = request.POST["fecha1"]
            vianda1.descripcion = request.POST["menu1"]
            vianda1.tipo = 'TRADICIONAL'
            vianda1.save()

            vianda2.estado='ACTIVA'
            vianda2.dia = 'LUNES'
            vianda2.fecha = request.POST["fecha1"]
            vianda2.descripcion = request.POST["menu2"]
            vianda2.tipo = 'LIGHT'
            vianda2.save()

            vianda3.estado='ACTIVA'
            vianda3.dia = 'LUNES'
            vianda3.fecha = request.POST["fecha1"]
            vianda3.descripcion = request.POST["menu3"]
            vianda3.tipo = 'VEGGIE'
            vianda3.save()

            #MARTES
            vianda4.estado='ACTIVA'
            vianda4.dia = 'MARTES'
            vianda4.fecha = request.POST["fecha2"]
            vianda4.descripcion = request.POST["menu4"]
            vianda4.tipo = 'TRADICIONAL'
            vianda4.save()

            vianda5.estado='ACTIVA'
            vianda5.dia = 'MARTES'
            vianda5.fecha = request.POST["fecha2"]
            vianda5.descripcion = request.POST["menu5"]
            vianda5.tipo = 'LIGHT'
            vianda5.save()

            vianda6.estado='ACTIVA'
            vianda6.dia = 'MARTES'
            vianda6.fecha = request.POST["fecha2"]
            vianda6.descripcion = request.POST["menu6"]
            vianda6.tipo = 'VEGGIE'
            vianda6.save()

            #MIERCOLES
            vianda7.estado='ACTIVA'
            vianda7.dia = 'MIERCOLES'
            vianda7.fecha = request.POST["fecha3"]
            vianda7.descripcion = request.POST["menu7"]
            vianda7.tipo = 'TRADICIONAL'
            vianda7.save()

            vianda8.estado='ACTIVA'
            vianda8.dia = 'MIERCOLES'
            vianda8.fecha = request.POST["fecha3"]
            vianda8.descripcion = request.POST["menu8"]
            vianda8.tipo = 'LIGHT'
            vianda8.save()

            vianda9.estado='ACTIVA'
            vianda9.dia = 'MIERCOLES'
            vianda9.fecha = request.POST["fecha3"]
            vianda9.descripcion = request.POST["menu9"]
            vianda9.tipo = 'VEGGIE'
            vianda9.save()

            #JUEVES
            vianda10.estado='ACTIVA'
            vianda10.dia = 'JUEVES'
            vianda10.fecha = request.POST["fecha4"]
            vianda10.descripcion = request.POST["menu10"]
            vianda10.tipo = 'TRADICIONAL'
            vianda10.save()

            vianda11.estado='ACTIVA'
            vianda11.dia = 'JUEVES'
            vianda11.fecha = request.POST["fecha4"]
            vianda11.descripcion = request.POST["menu11"]
            vianda11.tipo = 'LIGHT'
            vianda11.save()

            vianda12.estado='ACTIVA'
            vianda12.dia = 'JUEVES'
            vianda12.fecha = request.POST["fecha4"]
            vianda12.descripcion = request.POST["menu12"]
            vianda12.tipo = 'VEGGIE'
            vianda12.save()

            #VIERNES
            vianda13.estado='ACTIVA'
            vianda13.dia = 'VIERNES'
            vianda13.fecha = request.POST["fecha5"]
            vianda13.descripcion = request.POST["menu13"]
            vianda13.tipo = 'TRADICIONAL'
            vianda13.save()

            vianda14.estado='ACTIVA'
            vianda14.dia = 'VIERNES'
            vianda14.fecha = request.POST["fecha5"]
            vianda14.descripcion = request.POST["menu14"]
            vianda14.tipo = 'LIGHT'
            vianda14.save()

            vianda15.estado='ACTIVA'
            vianda15.dia = 'VIERNES'
            vianda15.fecha = request.POST["fecha5"]
            vianda15.descripcion = request.POST["menu15"]
            vianda15.tipo = 'VEGGIE'
            vianda15.save()
            

            return redirect('Recursos Humanos')

    else:
        form = FormCargaSemana()
    
    return render(request, 'cargar_semana.html', {"form": form})

#TODO Ver como editar semana - Mejora a futuro, podemos modificar desde admin.
def editar_semana(request):
    context = {}

    semana = Vianda.objects.filter(estado = 'ACTIVA')

    context['instance'] = semana

    if request.method == 'POST':
        form = FormCargaSemana(request.POST, instance=semana)
        if form.is_valid():
            form.save()
            return redirect('Tienda')
    else:
        form = FormCargaSemana(instance=semana)
    context['form'] = form
    return render(request, 'cargar_semana.html', context=context)


#ESTO HABRÍA QUE LLAMARLO LUEGO DE GENERAR EL REPORTE
@user_passes_test(es_rrhh)
def desactivar_viandas(request):

    viandas = Vianda.objects.filter(estado='ACTIVA')
    tamaños = Tamaño.objects.filter(estado='ACTIVA')
    pedidos = Pedido.objects.filter(estado='ACTIVO')
    for vianda in viandas:
        vianda.estado = 'INACTIVA'
        vianda.save()
    for tamaño in tamaños:
        tamaño.estado = 'INACTIVA'
        tamaño.save()
    for pedido in pedidos:
        pedido.estado = 'INACTIVO'
        pedido.save()

    return redirect(rrhh)



def siguiente(request):
    #test
    return render(request, "siguiente.html")

ComoQuieras/Cometela/templates/cargar_semana.html
{% extends 'base.html' %}

{% block contents %}

<!--
    Hacer un FORM para cargar las viandas de toda la semana con boton de cargar que habilite a los usuarios a realizar pedidos.
    Poder CERRAR el pedido semanal inhabilitando a los usuarios a realizar pedidos.
    Luego de cerrar una semana, poder exportar un archivo con todos los pedidos realizador. Ver en que formato y como mostrar los datos.
-->

<!--Validar que el usuario sea de RRHH-->
<form method="POST" action="">
    {% csrf_token %}
    <p>En caso de que algún día no haya vianda, rellenar los campos de los menús con un "-" </p>
    <div class="dia lunes mt-2">
        <h2>LUNES</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="fecha1" class="col-form-label">Fecha:</label>
            </div>
            <div class="col-auto ">
                <input name="fecha1" class="form-control" type="date">
            </div>
        </div>
        <div class="tipo tradicional mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu1" class="col-form-label">Tradicional</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu1" name="menu1" class="form-control">
            </div>
        </div>
        <div class="tipo light mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu2" class="col-form-label">Light</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu2" name="menu2" class="form-control">
            </div>
        </div>
        <div class="tipo veggie mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu3" class="col-form-label">Veggie</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu3" name="menu3" class="form-control">
            </div>
        </div>
    </div>

    <div class="dia martes mt-2">
        <h2>MARTES</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="fecha2" class="col-form-label">Fecha:</label>
            </div>
            <div class="col-auto">
                <input name="fecha2" class="form-control" type="date">
            </div>
        </div>
        <div class="tipo tradicional mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu4" class="col-form-label">Tradicional</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu4" name="menu4" class="form-control">
            </div>
        </div>
        <div class="tipo light mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu5" class="col-form-label">Light</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu5" name="menu5" class="form-control">
            </div>
        </div>
        <div class="tipo veggie mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu6" class="col-form-label">Veggie</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu6" name="menu6" class="form-control">
            </div>
        </div>
    </div>

    <div class="dia miercoles mt-2">
        <h2>MIERCOLES</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="fecha3" class="col-form-label">Fecha:</label>
            </div>
            <div class="col-auto">
                <input name="fecha3" class="form-control" type="date">
            </div>
        </div>
        <div class="tipo tradicional mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu7" class="col-from-label">Tradicional</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu7" name="menu7" class="form-control">
            </div>
        </div>
        <div class="tipo light mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu8" class="col-from-label">Light</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu8" name="menu8" class="form-control">
            </div>
        </div>
        <div class="tipo veggie mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu9" class="col-from-label">Veggie</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu9" name="menu9" class="form-control">
            </div>
        </div>
    </div>

    <div class="dia jueves mt-2">
        <h2>JUEVES</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="fecha4" class="col-form-label">Fecha:</label>
            </div>
            <div class="col-auto">
                <input name="fecha4" class="form-control" type="date">
            </div>
        </div>
        <div class="tipo tradicional mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu10" class="col-from-label">Tradicional</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu10" name="menu10" class="form-control">
            </div>
        </div>
        <div class="tipo light mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu11" class="col-from-label">Light</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu11" name="menu11" class="form-control">
            </div>
        </div>
        <div class="tipo veggie mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu12" class="col-from-label">Veggie</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu12" name="menu12" class="form-control">
            </div>
        </div>
    </div>

    <div class="dia viernes mt-2">
        <h2>VIERNES</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="fecha5" class="col-form-label">Fecha:</label>
            </div>
            <div class="col-auto">
                <input name="fecha5" class="form-control" type="date">
            </div>
        </div>
        <div class="tipo tradicional mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu13" class="col-from-label">Tradicional</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu13" name="menu13" class="form-control">
            </div>
        </div>
        <div class="tipo light mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu14" class="col-from-label">Light</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu14" name="menu14" class="form-control">
            </div>
        </div>
        <div class="tipo veggie mt-1 row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_menu15" class="col-from-label">Veggie</label>
            </div>
            <div class="col-6">
                <input type="text" id="id_menu15" name="menu15" class="form-control">
            </div>
        </div>
    </div>

    <div class="precios mt-2">
        <h2>PRECIOS</h2>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_precio_media" class="col-form-label">Media</label>
            </div>
            <div class="col-auto">
                <input type="text" id="id_precio_media" name="precio_media" class="form-control">
            </div>
        </div>
        <div class="row">
            <div class="col-auto col-lg-1 col-2">
                <label for="id_precio_entera" class="col-form-label">Entera</label>
            </div>
            <div class="mt-1 col-auto">
                <input type="text" id="id_precio_entera" name="precio_entera" class="form-control">
            </div>  
        </div>
    </div>

    <a href="{% url 'Tienda' %}" class="btn btn-danger mt-4 mb-4">VOLVER</a>
    <button type="button" class="btn btn-success mt-4 mb-4" data-toggle="modal" data-target="#CargarSemanaModal">
        CARGAR SEMANA
    </button>
    <!-- Modal -->
    <div class="modal fade" id="CargarSemanaModal" tabindex="-1" role="dialog" aria-labelledby="CargarSemanaModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="CargarSemanaModalTitle">CONFIRMAR CARGA DE SEMANA</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Revisar que los menús estén correctamente cargados!</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Volver</button>
                    <button class="btn btn-success" type="submit">CARGAR</button>
                </div>
            </div>
        </div>
    </div>
</form>



{% endblock %}

ComoQuieras/Cometela/templates/historial.html
{% extends 'base.html' %}

{% block contents %}

<div class="col-12 justify-content-center">
    {% for pedido in lista_pedidos %}
        <div class="card mt-4 mb-4">
            <div class="card-body">
                <h5 class="card-title">{{pedido.created_at}}</h5>
            </div>
            {% for linea in lista_lineas_pedidos %}
                {% if linea.pedido == pedido %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <p>
                            {{linea.vianda_tamaño.vianda.fecha}} - <b>{{linea.vianda_tamaño.vianda.dia}}</b> - <b>{{linea.vianda_tamaño.vianda.tipo}}</b> - <b>{{linea.vianda_tamaño.tamaño.tamaño}}</b> - Cantidad: {{linea.cantidad}} - Menú: {{linea.vianda_tamaño.vianda.descripcion}}
                        </p>
                    </li>
                </ul>
                {% endif %}
            {% endfor %}
            <b><p style="margin: 1rem;">Precio: ${{pedido.total}}</p></b>
        </div>
    {% endfor %}
    <a href="{% url 'Tienda' %}" class="btn btn-primary mt-4 mb-4">VOLVER</a>
</div>

{% endblock %}